"""add transference table

Revision ID: 981608b2cfa6
Revises: 4b94d65713ae
Create Date: 2025-09-20 21:17:35.529966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '981608b2cfa6'
down_revision: Union[str, Sequence[str], None] = '4b94d65713ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transference',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('from_account_number', sa.Uuid(), nullable=False),
    sa.Column('to_account_number', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['from_account_number'], ['account.number'], ),
    sa.ForeignKeyConstraint(['to_account_number'], ['account.number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transference')
    # ### end Alembic commands ###
